config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :child__models
  namespace :admin do
    resources :parent_models
  end
  scope :admin do
    resources :koko
  end
  resources :examples
  resources :book
  resources :lol
  get '/bewks', to: 'book#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/child__model.rb
class ChildModel < ApplicationRecord
end

app/controllers/child__models_controller.rb
class ChildModelsController < ApplicationController
  before_action :set_child__model, only: %i[ show edit update destroy ]

  # GET /child__models or /child__models.json
  def index
    @child__models = ChildModel.all
  end

  # GET /child__models/1 or /child__models/1.json
  def show
  end

  # GET /child__models/new
  def new
    @child__model = ChildModel.new
  end

  # GET /child__models/1/edit
  def edit
  end

  # POST /child__models or /child__models.json
  def create
    @child__model = ChildModel.new(child__model_params)

    respond_to do |format|
      if @child__model.save
        format.html { redirect_to child__model_url(@child__model), notice: "Child  model was successfully created." }
        format.json { render :show, status: :created, location: @child__model }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @child__model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /child__models/1 or /child__models/1.json
  def update
    respond_to do |format|
      if @child__model.update(child__model_params)
        format.html { redirect_to child__model_url(@child__model), notice: "Child  model was successfully updated." }
        format.json { render :show, status: :ok, location: @child__model }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @child__model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /child__models/1 or /child__models/1.json
  def destroy
    @child__model.destroy

    respond_to do |format|
      format.html { redirect_to child__models_url, notice: "Child  model was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_child__model
      @child__model = ChildModel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def child__model_params
      params.fetch(:child__model, {})
    end
end

app/helpers/child__models_helper.rb
module ChildModelsHelper
end

app/views/child__models/_form.html.erb
<%= form_with(model: child__model, local: true) do |form| %>
  <% if child__model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(child__model.errors.count, "error") %> prohibited this child__model from being saved:</h2>

      <ul>
      <% child__model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/child__models/edit.html.erb
<h1>Editing Child  Model</h1>

<%= render 'form', child__model: @child__model %>

<%= link_to 'Show', @child__model %> |
<%= link_to 'Back', child__models_path %>

app/views/child__models/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Child  Models</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @child__models.each do |child__model| %>
      <tr>
        <td><%= link_to 'Show', child__model %></td>
        <td><%= link_to 'Edit', edit_child__model_path(child__model) %></td>
        <td><%= link_to 'Destroy', child__model, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Child  Model', new_child__model_path %>

app/views/child__models/new.html.erb
<h1>New Child  Model</h1>

<%= render 'form', child__model: @child__model %>

<%= link_to 'Back', child__models_path %>

app/views/child__models/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_child__model_path(@child__model) %> |
<%= link_to 'Back', child__models_path %>