config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :child__models
  namespace :admin do
    resources :parent_models
  end
  scope :admin do
    resources :koko
  end
  resources :examples
  resources :book
  resources :lol
  get '/bewks', to: 'book#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/parent_model.rb
class ParentModel < ApplicationRecord
end

app/controllers/parent_models_controller.rb
class ParentModelsController < ApplicationController
  before_action :set_parent_model, only: %i[ show edit update destroy ]

  # GET /parent_models or /parent_models.json
  def index
    @parent_models = ParentModel.all
  end

  # GET /parent_models/1 or /parent_models/1.json
  def show
  end

  # GET /parent_models/new
  def new
    @parent_model = ParentModel.new
  end

  # GET /parent_models/1/edit
  def edit
  end

  # POST /parent_models or /parent_models.json
  def create
    @parent_model = ParentModel.new(parent_model_params)

    respond_to do |format|
      if @parent_model.save
        format.html { redirect_to parent_model_url(@parent_model), notice: "Parent model was successfully created." }
        format.json { render :show, status: :created, location: @parent_model }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @parent_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parent_models/1 or /parent_models/1.json
  def update
    respond_to do |format|
      if @parent_model.update(parent_model_params)
        format.html { redirect_to parent_model_url(@parent_model), notice: "Parent model was successfully updated." }
        format.json { render :show, status: :ok, location: @parent_model }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @parent_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parent_models/1 or /parent_models/1.json
  def destroy
    @parent_model.destroy

    respond_to do |format|
      format.html { redirect_to parent_models_url, notice: "Parent model was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parent_model
      @parent_model = ParentModel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def parent_model_params
      params.fetch(:parent_model, {})
    end
end

app/helpers/parent_models_helper.rb
module ParentModelsHelper
end

app/views/parent_models/_form.html.erb
<%= form_with(model: parent_model, local: true) do |form| %>
  <% if parent_model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(parent_model.errors.count, "error") %> prohibited this parent_model from being saved:</h2>

      <ul>
      <% parent_model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/parent_models/edit.html.erb
<h1>Editing Parent Model</h1>

<%= render 'form', parent_model: @parent_model %>

<%= link_to 'Show', @parent_model %> |
<%= link_to 'Back', parent_models_path %>

app/views/parent_models/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Parent Models</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parent_models.each do |parent_model| %>
      <tr>
        <td><%= link_to 'Show', parent_model %></td>
        <td><%= link_to 'Edit', edit_parent_model_path(parent_model) %></td>
        <td><%= link_to 'Destroy', parent_model, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Parent Model', new_parent_model_path %>

app/views/parent_models/new.html.erb
<h1>New Parent Model</h1>

<%= render 'form', parent_model: @parent_model %>

<%= link_to 'Back', parent_models_path %>

app/views/parent_models/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_parent_model_path(@parent_model) %> |
<%= link_to 'Back', parent_models_path %>